# Generated by Django 3.2.7 on 2021-09-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=32)),
                ('model_name', models.CharField(max_length=32)),
                ('ram', models.IntegerField(null=True)),
                ('rom', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
    ]
