# Generated by Django 3.2.8 on 2021-10-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('previous_visit', models.CharField(max_length=50)),
                ('if_before_visited_visit_detail', models.CharField(max_length=50)),
                ('appointment_date', models.DateField()),
                ('slot', models.CharField(max_length=30)),
                ('contact_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
