# Generated by Django 3.2.8 on 2021-10-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthify', '0002_auto_20211021_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('qualification', models.CharField(choices=[('BHMS', 'BHMS'), ('BAMS', 'BAMS'), ('MBBS', 'MBBS'), ('Physiotherapists', 'Physiothrapists'), ('MD', 'MD')], max_length=50)),
                ('aadhaar_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NursingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('qualification', models.CharField(choices=[('BSC Nursing', 'BSC Nursing'), ('Graduation+Nursing Course', 'Graduation+Nursing Course')], max_length=50)),
                ('aadhaar_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomServiceStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('aadhaar_number', models.CharField(max_length=50)),
            ],
        ),
    ]
