# Generated by Django 3.2.8 on 2021-10-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthify', '0004_auto_20211026_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
