# Generated by Django 4.0.3 on 2022-03-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='admin_response',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='question',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Railway', 'Railway'), ('Aeroplane', 'Aeroplane')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
