# Generated by Django 4.0.3 on 2022-03-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketApp', '0002_rename_user_customer_rename_user_order_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Travelling', 'Travelling'), ('Movie', 'Movie'), ('Tourism', 'Tourism')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
