# Generated by Django 3.2.8 on 2021-10-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=32)),
                ('emob', models.IntegerField()),
                ('edesignation', models.CharField(max_length=32)),
                ('esal', models.FloatField()),
                ('ecity', models.CharField(max_length=32)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
