# Generated by Django 3.2.8 on 2021-10-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default=2, upload_to='myimage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
