# Generated by Django 3.2.7 on 2021-09-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aname', models.CharField(max_length=10)),
                ('Acolor', models.CharField(max_length=10)),
                ('Alegs', models.IntegerField()),
                ('Afoundin', models.CharField(max_length=10)),
                ('Apet', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('Ename', models.CharField(max_length=10)),
                ('Ecity', models.CharField(max_length=10)),
                ('Emobno', models.IntegerField()),
                ('Edesignation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lname', models.CharField(max_length=10)),
                ('Lgeneration', models.CharField(max_length=10)),
                ('Lram', models.CharField(max_length=10)),
                ('Lhd', models.CharField(max_length=10)),
                ('Lcolor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField()),
                ('Pname', models.CharField(max_length=10)),
                ('Pmfg', models.CharField(max_length=10)),
                ('Pexp', models.CharField(max_length=10)),
                ('Pprice', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('standard', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=10)),
            ],
        ),
    ]
