# Generated by Django 3.2.7 on 2021-09-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_laptop_lprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='Eaddress',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
