# Generated by Django 3.2.7 on 2021-09-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0003_employer_eaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='Eaddress',
            field=models.CharField(default='abc', max_length=10),
        ),
    ]
