# Generated by Django 4.0.3 on 2022-04-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_author_id_alter_book_id_alter_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
    ]
