# Generated by Django 3.2.7 on 2021-09-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='abc', max_length=20),
        ),
    ]
