# Generated by Django 3.2.7 on 2021-09-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('mobno', models.IntegerField()),
                ('designation', models.CharField(max_length=32)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
