# Generated by Django 3.2.8 on 2021-10-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0003_auto_20211014_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_img',
            field=models.ImageField(upload_to='myimage'),
        ),
    ]
