# Generated by Django 3.2.8 on 2021-10-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0004_alter_employee_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='profile_img',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
